# 请求服务配置
forest:
  async-mode: platform
  connect-timeout: 300000
  read-timeout: 300000
  timeout: 300000
  variables:
    apiKey: sk-8c24f6784f094f2da128e3f09c108296
    mogudingApi: 'https://api.moguding.net:9000'
    userAgent: 'Mozilla/5.0 (Linux; U; Android 9; zh-cn; Redmi Note 5 Build/PKQ1.180904.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/11.10.8'
  log-enabled: false
  log-response-status: false

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "@ghe021213"
    url: jdbc:mysql://101.200.193.24:3306/autosign

  #发送邮件
  mail:
    host: smtp.163.com
    username: simbot@163.com
    password: UWZVBUOGQRFVOQET
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          port: 465
          timeout: 5000
# mybatis-plus配置
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
